image: docker:stable
services:
  - docker:dind

stages:
  - build
  - release
#  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_DEVELOP_IMAGE: $CI_REGISTRY_IMAGE:develop
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_DEVELOP_IMAGE || true
    - docker build --cache-from $CONTAINER_DEVELOP_IMAGE --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

develop-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_DEVELOP_IMAGE
    - docker push $CONTAINER_DEVELOP_IMAGE
  only:
    - develop

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

#  deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - master
